version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # 필요한 경우 Java 버전을 corretto11에서 corretto17로 변경
  build:
    commands:
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar  # Gradle 빌드 결과물이 저장되는 디렉터리
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
